---
version: "3"
services:
    beef:
        image: ilyaglow/beef
        hostname: beef
        container_name: beef
        ports:
            - 3000:3000
            - 6789:6789
            - 61985:61985
            - 61986:61986
        environment:
            - BEEF_USER=admin
            - BEEF_PASSWORD=admin123
        volumes:
            - ./html:/home/beef/beef/extensions/demos/html/
# http://localhost:3000/ui/panel

#docker run -itd \
#           --name=beef \
#           -p 3000:3000 \
#           -p 6789:6789 \
#           -p 61985:61985 \
#           -p 61986:61986 \
#           -e BEEF_USER=admin \
#           -e BEEF_PASSWORD=admin123 \
#           ilyaglow/beef